export const product = {
  name: "Invoice Follow-up",
  tagline: "Track existing invoices and automate payment recovery",
  domain: "invoicefollow.devforgeapp.pro",
  url: "https://invoicefollow.devforgeapp.pro",
  accentColor: "#821346",
  keyword: "invoice follow up tool",
  seoTitle: "Invoice Follow-up - Automated Payment Recovery | DevForge",
  seoDescription: "Stop chasing payments manually. Track existing invoices, record payment progress, classify replies, and automate follow-ups via email. Pro starts at $9.99/mo.",
  navLinks: [{ label: "Features", href: "#features" }, { label: "Pricing", href: "#pricing" }],
  hero: {
    badge: "Get Paid Faster",
    headline: "Never Chase a Payment Again.",
    subtitle: "Track existing invoices from CSV, PDF workflows, or a safe tracking form. InvoiceFollow handles reminders, reply classification, partial payments, and approvals.",
    ctaText: "Start Free",
    ctaHref: "/register",
    secondaryCtaText: "See How It Works",
    secondaryCtaHref: "#features",
  },
  features: [
    { title: "Smart Reminders", description: "Use the 0, 7, 15, 30, and 45 day recovery sequence with sender escalation." },
    { title: "Payment Progress", description: "Record partial payments, disputes, approvals, and settled invoices without losing the remaining balance." },
    { title: "Reply Classification", description: "Classify paid claims, valid excuses, false excuses, and manual-review replies." },
  ],
  pricing: {
    planName: "Pro",
    price: 9.99,
    description: "50 active invoices, payment progress, custom templates, and weekly digest",
    polarProductId: process.env.NEXT_PUBLIC_POLAR_PRODUCT_ID || process.env.NEXT_PUBLIC_POLAR_PRODUCT_ID_INVOICEFOLLOW || "",
    features: [
      { text: "50 active invoices", included: true },
      { text: "Automated email reminders", included: true },
      { text: "Partial payments and manual approvals", included: true },
      { text: "Custom templates and weekly digest", included: true },
      { text: "Additional Team users", included: false },
    ],
  },
  testimonials: [
    { quote: "Cut my overdue invoices by 60% in the first month. The automated reminders are a game-changer.", name: "Lisa Wong", role: "Freelance Designer" },
    { quote: "Simple and effective. No bloated accounting software needed.", name: "David Moreno", role: "Web Developer" },
    { quote: "My clients actually appreciate the professional follow-up emails.", name: "Emma Clark", role: "Consultant" },
  ],
  dashboardNav: [
    { label: "Invoices", href: "/dashboard" },
    { label: "Settings", href: "/dashboard/settings" },
  ],
  plausibleDomain: "invoicefollow.devforgeapp.pro",
} as const;
