export const product = {
  name: "Feedback Lens",
  tagline: "AI-powered sentiment analysis for customer feedback",
  domain: "feedbacklens.devforgeapp.pro",
  url: "https://feedbacklens.devforgeapp.pro",
  accentColor: "#821346",
  keyword: "feedback lens AI",
  seoTitle: "Feedback Lens — AI Sentiment Analysis for User Feedback | DevForge",
  seoDescription: "Collect user feedback and instantly analyze sentiment with Gemini AI. Spot trends, prioritize issues, and understand your users. Only $9.99/mo.",
  navLinks: [{ label: "Features", href: "#features" }, { label: "Pricing", href: "#pricing" }],
  hero: {
    badge: "AI-Powered",
    headline: "Understand Your Users. Automatically.",
    subtitle: "Collect feedback from any source, run AI sentiment analysis with Gemini, and surface the insights that matter most.",
    ctaText: "Start 7-Day Free Trial",
    ctaHref: "/register",
    secondaryCtaText: "See Features",
    secondaryCtaHref: "#features",
  },
  features: [
    { title: "AI Sentiment Analysis", description: "Powered by Google Gemini. Automatically classify feedback as positive, negative, or neutral with confidence scores." },
    { title: "Feedback Collection", description: "Paste feedback manually, import from CSV, or use our API. Aggregate feedback from multiple channels in one place." },
    { title: "Trend Detection", description: "Spot recurring themes and emerging issues before they become problems. Weekly digest with key insights." },
  ],
  pricing: {
    planName: "Pro",
    price: 9.99,
    description: "Unlimited feedback & AI analysis",
    lsVariantId: process.env.NEXT_PUBLIC_LS_VARIANT_ID || process.env.NEXT_PUBLIC_LS_VARIANT_ID_FEEDBACKLENS || "",
    features: [
      { text: "Unlimited feedback entries", included: true },
      { text: "AI sentiment analysis", included: true },
      { text: "Theme detection", included: true },
      { text: "CSV import/export", included: true },
      { text: "Slack integration", included: false },
    ],
  },
  testimonials: [
    { quote: "The AI analysis is surprisingly accurate. Saved us from reading 500 feedback entries manually.", name: "Anna Foster", role: "Product Manager" },
    { quote: "We pipe all our support tickets through this. The trend detection caught a UX issue we missed.", name: "James Wu", role: "UX Lead" },
    { quote: "Clean, fast, and the AI actually works. No gimmicks.", name: "Olivia Santos", role: "Founder" },
  ],
  dashboardNav: [
    { label: "Feedback", href: "/dashboard" },
    { label: "Settings", href: "/dashboard/settings" },
  ],
  plausibleDomain: "feedbacklens.devforgeapp.pro",
} as const;
