export const product = {
  name: "Feedback Lens",
  tagline: "Local sentiment analysis for customer feedback",
  domain: "feedbacklens.devforgeapp.pro",
  url: "https://feedbacklens.devforgeapp.pro",
  accentColor: "#821346",
  keyword: "feedback sentiment analysis",
  seoTitle: "Feedback Lens - Local Sentiment Analysis for User Feedback | DevForge",
  seoDescription: "Collect user feedback, classify sentiment locally, deduplicate repeated complaints, and spot the issues your team should handle next. Pro starts at $19/mo.",
  navLinks: [{ label: "Features", href: "#features" }, { label: "Pricing", href: "#pricing" }],
  hero: {
    badge: "Local Analysis",
    headline: "Understand Your Users. Automatically.",
    subtitle: "Collect feedback from any source, run local sentiment analysis, group repeated issues, and surface the insights that matter most.",
    ctaText: "Start 7-Day Free Trial",
    ctaHref: "/register",
    secondaryCtaText: "See Features",
    secondaryCtaHref: "#features",
  },
  features: [
    { title: "Local Sentiment Analysis", description: "Classify feedback as positive, negative, or neutral with confidence scores without relying on external generation APIs." },
    { title: "Feedback Collection", description: "Paste feedback manually, import from CSV, or use our API. Aggregate feedback from multiple channels in one place." },
    { title: "Deduped Trend Detection", description: "Spot recurring themes and emerging issues without inflating counts from near-duplicate feedback." },
  ],
  pricing: {
    planName: "Pro",
    price: 19,
    description: "5000 feedback items per month with local analysis",
    polarProductId: process.env.NEXT_PUBLIC_POLAR_PRODUCT_ID || process.env.NEXT_PUBLIC_POLAR_PRODUCT_ID_FEEDBACKLENS || "",
    features: [
      { text: "5000 feedback items/month", included: true },
      { text: "Local sentiment analysis", included: true },
      { text: "Theme detection", included: true },
      { text: "Near-duplicate detection", included: true },
      { text: "CSV import/export", included: true },
      { text: "GitHub, Canny, X, and Reddit sources", included: true },
    ],
  },
  testimonials: [
    { quote: "The local analysis is fast enough for our weekly triage and the dedupe keeps counts honest.", name: "Anna Foster", role: "Product Manager" },
    { quote: "We pipe all our support tickets through this. The trend detection caught a UX issue we missed.", name: "James Wu", role: "UX Lead" },
    { quote: "Clean, fast, and predictable. No external model surprises in the middle of launch week.", name: "Olivia Santos", role: "Founder" },
  ],
  dashboardNav: [
    { label: "Feedback", href: "/dashboard" },
    { label: "Settings", href: "/dashboard/settings" },
  ],
  plausibleDomain: "feedbacklens.devforgeapp.pro",
} as const;
