import { sql } from "../../../lib/db";
import { notFound } from "next/navigation";
import Link from "next/link";
import { ExternalLink, ChevronLeft, ShoppingCart, Tag, Calendar, Activity } from "lucide-react";
import TakedownForm from "./components/TakedownForm";
import { Metadata } from "next";

export const revalidate = 3600; // Revalidate every hour

/* eslint-disable @next/next/no-img-element -- The chart is a dynamic SVG generated by the backend and should render as-is. */

function normalizeStaticSlug(value: unknown): string | null {
  if (typeof value !== "string") return null;
  const slug = value.trim();
  return /^[a-z0-9][a-z0-9-]{1,120}$/i.test(slug) ? slug : null;
}

// Generate dynamic sitemap paths
export async function generateStaticParams() {
  const publicSlugs = await sql`
    SELECT slug::text AS slug FROM tracked_urls
    WHERE is_public = TRUE AND status != 'deleted'
  `;
  return publicSlugs
    .map((p: any) => normalizeStaticSlug(p.slug))
    .filter((slug: string | null): slug is string => Boolean(slug))
    .map((slug: string) => ({ slug }));
}

export async function generateMetadata({
  params,
}: {
  params: { slug: string };
}): Promise<Metadata> {
  const products = await sql`
    SELECT label, current_price FROM tracked_urls
    WHERE slug = ${params.slug} AND is_public = TRUE AND status != 'deleted'
    LIMIT 1
  `;

  if (products.length === 0) {
    return {
      title: "Product Not Found | PriceTrackr",
    };
  }

  const p = products[0];
  const priceDisplay = p.current_price !== null ? `$${parseFloat(p.current_price).toFixed(2)}` : "monitoring";

  return {
    title: `${p.label} Price History & Drops | PriceTrackr`,
    description: `Track real-time pricing updates for ${p.label}. Currently priced at ${priceDisplay}. View detailed price charts and analytics.`,
  };
}

export default async function ProductDetailPage({ params }: { params: { slug: string } }) {
  const products = await sql`
    SELECT id, label, url, current_price, min_price, in_stock, last_checked, created_at, slug
    FROM tracked_urls
    WHERE slug = ${params.slug} AND is_public = TRUE AND status != 'deleted'
    LIMIT 1
  `;

  if (products.length === 0) {
    notFound();
  }

  const p = products[0];
  const apiUrl = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";
  const hasPrice = p.current_price !== null;

  return (
    <div className="min-h-screen bg-black text-white p-6 md:p-12">
      <div className="max-w-4xl mx-auto space-y-8">

        {/* Back Link */}
        <Link
          href="/p"
          className="inline-flex items-center gap-1.5 text-xs text-zinc-500 hover:text-white transition-colors uppercase tracking-wider font-bold"
        >
          <ChevronLeft className="w-3.5 h-3.5" />
          <span>Back to products</span>
        </Link>

        {/* Product Details Section */}
        <div className="bg-zinc-950/30 border border-white/5 rounded-2xl p-6 md:p-8 space-y-6">

          <div className="flex flex-col md:flex-row md:items-start justify-between gap-6 border-b border-white/5 pb-6">
            <div className="space-y-2">
              <span
                className={`text-[9px] font-extrabold uppercase px-2 py-0.5 rounded ${
                  p.in_stock !== false
                    ? "bg-emerald-500/10 text-emerald-400 border border-emerald-500/25"
                    : "bg-red-500/10 text-red-400 border border-red-500/25"
                }`}
              >
                {p.in_stock !== false ? "In Stock" : "Out of Stock"}
              </span>
              <h1 className="text-2xl md:text-3xl font-extrabold tracking-tight text-white leading-tight">
                {p.label}
              </h1>
              <p className="text-xs text-zinc-500 truncate max-w-lg">{p.url}</p>
            </div>

            <div className="flex flex-row md:flex-col items-center md:items-end justify-between md:justify-start gap-4">
              <div className="text-left md:text-right">
                <span className="text-[9px] text-zinc-500 font-bold uppercase tracking-wider">Current Price</span>
                <p className="text-2xl font-extrabold font-mono text-indigo-400 leading-none mt-1">
                  {hasPrice ? `$${parseFloat(p.current_price).toFixed(2)}` : "Monitoring..."}
                </p>
              </div>

              <a
                href={p.url}
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center gap-1 px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg text-xs font-semibold transition-colors"
              >
                <span>Buy Product</span>
                <ExternalLink className="w-3.5 h-3.5" />
              </a>
            </div>
          </div>

          {/* Price statistics cards */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div className="p-4 rounded-xl bg-zinc-900/60 border border-white/5 space-y-1">
              <span className="text-[9px] text-zinc-500 font-bold uppercase tracking-wider flex items-center gap-1">
                <Tag className="w-3 h-3" /> Minimum Price Recorded
              </span>
              <p className="text-lg font-bold font-mono text-emerald-400">
                {p.min_price !== null ? `$${parseFloat(p.min_price).toFixed(2)}` : "—"}
              </p>
            </div>

            <div className="p-4 rounded-xl bg-zinc-900/60 border border-white/5 space-y-1">
              <span className="text-[9px] text-zinc-500 font-bold uppercase tracking-wider flex items-center gap-1">
                <Calendar className="w-3 h-3" /> Monitoring Since
              </span>
              <p className="text-sm font-semibold text-zinc-200">
                {p.created_at ? new Date(p.created_at).toLocaleDateString() : "—"}
              </p>
            </div>

            <div className="p-4 rounded-xl bg-zinc-900/60 border border-white/5 space-y-1">
              <span className="text-[9px] text-zinc-500 font-bold uppercase tracking-wider flex items-center gap-1">
                <Activity className="w-3 h-3" /> Last Checked
              </span>
              <p className="text-sm font-semibold text-zinc-200">
                {p.last_checked ? new Date(p.last_checked).toLocaleString() : "—"}
              </p>
            </div>
          </div>

          {/* SVG Price History Embed from Render */}
          <div className="space-y-2">
            <h3 className="text-xs font-bold text-zinc-400 uppercase tracking-wider">Price History Chart</h3>
            <div className="relative aspect-[5/2] w-full overflow-hidden rounded-xl border border-white/5 bg-zinc-950/40">
              <img
                src={`${apiUrl}/public/pricetrackr/trackers/${p.id}/history.svg`}
                alt="Product price history chart"
                className="w-full h-full object-contain"
              />
            </div>
            <p className="text-[10px] text-zinc-500 text-center">
              Historical chart generated in real-time by Render background services.
            </p>
          </div>

        </div>

        {/* Takedown Request Area */}
        <div className="pt-6 border-t border-white/5">
          <TakedownForm slug={p.slug} apiUrl={apiUrl} />
        </div>

      </div>
    </div>
  );
}
