export const product = {
  name: "Webhook Monitor",
  tagline: "Receive, inspect, and replay webhooks in real time",
  domain: "webhookmonitor.devforgeapp.pro",
  url: "https://webhookmonitor.devforgeapp.pro",
  accentColor: "#821346",
  keyword: "webhook monitor tool",
  seoTitle: "Webhook Monitor — Inspect & Replay Webhooks in Real Time | DevForge",
  seoDescription: "Debug webhooks without ngrok. Get a unique URL, inspect every request in real time, and replay failed payloads. Only $9.99/mo.",
  navLinks: [{ label: "Features", href: "#features" }, { label: "Pricing", href: "#pricing" }],
  hero: {
    badge: "Developer Tool",
    headline: "Debug Webhooks Without the Pain.",
    subtitle: "Get a unique endpoint URL, see every incoming request in real time with full headers and body, and replay any payload with one click.",
    ctaText: "Start 7-Day Free Trial",
    ctaHref: "/register",
    secondaryCtaText: "See Features",
    secondaryCtaHref: "#features",
  },
  features: [
    { title: "Unique Endpoints", description: "Get a stable, unique URL for each project. Route webhooks from Stripe, GitHub, or any service." },
    { title: "Real-Time Log", description: "See requests as they arrive — method, headers, body, timing. Filter by status code or method." },
    { title: "Replay & Forward", description: "Replay any request to your local dev server. Forward webhooks to multiple destinations." },
  ],
  pricing: {
    planName: "Pro",
    price: 9.99,
    description: "Unlimited endpoints & requests",
    lsVariantId: process.env.NEXT_PUBLIC_LS_VARIANT_ID || process.env.NEXT_PUBLIC_LS_VARIANT_ID_WEBHOOKMONITOR || "",
    features: [
      { text: "Unlimited endpoints", included: true },
      { text: "Real-time request log", included: true },
      { text: "Request replay", included: true },
      { text: "30-day history", included: true },
      { text: "Team sharing", included: false },
    ],
  },
  testimonials: [
    { quote: "Replaced ngrok + webhook.site for our entire team. The replay feature is killer.", name: "Chris Park", role: "Backend Engineer" },
    { quote: "Essential for testing Stripe webhooks locally. Clean UI too.", name: "Nina Vargas", role: "Full-Stack Developer" },
    { quote: "The real-time log makes debugging webhook issues trivial.", name: "Ryan O'Brien", role: "DevOps Engineer" },
  ],
  dashboardNav: [
    { label: "Requests", href: "/dashboard" },
    { label: "Settings", href: "/dashboard/settings" },
  ],
  plausibleDomain: "webhookmonitor.devforgeapp.pro",
} as const;
